spring.application.name=fno


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mr.smohapatro@gmail.com
spring.mail.password=uikh rrnj tiul qtcz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true